#version: '3'
#services:
#  selenium-hub:
#    image: selenium/hub
#    ports:
#      - "4444:4444"
#    environment:
#      - GRID_MAX_SESSION=5
#
#  chrome:
#    image: selenium/node-chrome
#    environment:
#      - HUB_HOST=selenium-hub
#    depends_on:
#      - selenium-hub
#
#  firefox:
#    image: selenium/node-firefox
#    environment:
#      - HUB_HOST=selenium-hub
#    depends_on:
#      - selenium-hub

version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.28.1
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.28.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.28.1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
